name: user_repository
description: Dart package which manages the user domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  meta: ^1.3.0
  authentication_repository:
    path: ../authentication_repository
  user_api:
    path: ../user_api
  very_good_analysis: ^3.0.1
  dospace: ^0.13.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
