name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.3
  amplify_core: <1.0.0
  amplify_flutter: ^0.4.0
  amplify_auth_cognito: <1.0.0
  flutter:
    sdk: flutter
  meta: ^1.3.0
  very_good_analysis: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
