name: vote_circle_api
description: Vote and Circle API client.
version: 1.0.0
homepage: ''

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  graphql: ^5.1.1
  json_annotation: ^4.5.0
  equatable: ^2.0.3
  authentication_repository:
    path: ../authentication_repository
  logger: ^1.1.0

dev_dependencies:
  coverage: ^1.0.3
  build_runner: ^2.0.0
  test: ^1.16.4
  json_serializable: ^6.0.0
  graphql_codegen: ^0.8.1