name: vote_circle_repository
description: Dart package which manages the votes and circles domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  meta: ^1.3.0
  authentication_repository:
    path: ../authentication_repository
  vote_circle_api:
    path: ../vote_circle_api
  very_good_analysis: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
